services:
  postgres:
    image: postgres:16
    container_name: find-a-friend-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=find_a_friend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
